version: "3.8"

services:
  db:
    container_name: db
    build:
      context: .
      dockerfile: ./docker/db
    image: hikup/db
    logging:
      options:
        max-size: "1m"
    environment:
      POSTGRES_USER_FILE: /tmp/.secrets/db/user
      POSTGRES_PASSWORD_FILE: /tmp/.secrets/db/passwd
      POSTGRES_DB_FILE: /tmp/.secrets/db/db
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "172.19.0.1:5432:5432"
    networks:
      network:
        ipv4_address: 172.19.0.2
    stdin_open: true
    tty: true

  redis:
    container_name: redis
    build:
      context: .
      dockerfile: ./docker/redis
    image: hikup/redis
    logging:
      options:
        max-size: "1m"
    ports:
      - "172.19.0.1:6379:6379"
    volumes:
      - redis:/data
    networks:
      network:
        ipv4_address: 172.19.0.3
    stdin_open: true
    tty: true
    depends_on:
      - db

  api:
    container_name: api
    build:
      context: .
      dockerfile: ./docker/api
    image: hikup/api
    logging:
      options:
        max-size: "1m"
    command: [ "${API_CMD}" ]
    volumes:
      - ./server/api/src:/usr/app/src:ro
      - ./server/api/dist:/usr/app/dist:rw
      - ./server/api/config:/usr/app/config:ro
      - ./server/api/node_modules:/usr/app/node_modules:rw

      - ./server/api/package.json:/usr/app/package.json:rw
      - ./server/api/yarn.lock:/usr/app/yarn.lock:rw

      - prisma:/usr/prisma:rw
    ports:
      - "172.19.0.1:8443:8443"
      - "127.0.0.1:42042:42042"
    networks:
      network:
        ipv4_address: 172.19.0.4
    stdin_open: true
    tty: true
    depends_on:
      - db
      - redis

  nginx:
    container_name: nginx
    build:
      context: .
      dockerfile: ./docker/nginx
    image: hikup/nginx
    logging:
      options:
        max-size: "1m"
    command: [ "${NGINX_CMD}" ]
    ports:
      - "443:443"
    networks:
      network:
        ipv4_address: 172.19.0.5
    stdin_open: true
    tty: true
    depends_on:
      - db
      - redis
      - api

networks:
  network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "172.19.0.0/16"
          gateway: "172.19.0.1"

volumes:
  postgres:
  redis:
  prisma:
