on:
  push

name: ci

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v3

#      - name: install docker
#        shell: bash
#        run: ./scripts/actions.sh

      - name: install backend
        shell: bash
        run: ./backend.sh install

      - name: requirements
        shell: bash
        run: |
          touch ./server/ssl/privkey1.pem
          touch ./server/ssl/cert1.pem
          touch ./server/ssl/chain1.pem
          touch ./server/api/config/.env.test
          sudo chown -R 1000:1000 $(pwd)

      - name: start database
        shell: bash
        run: ./backend.sh db start

      - name: test api
        shell: bash
        run: ./backend.sh api test
