on:
  push:
    branches:
      - master
      - dev
      - actions
  workflow_dispatch:

name: ci

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: install backend
        shell: bash
        run: ./server.sh install

      - name: requirements
        shell: bash
        env:
          TEST_ENV: ${{ secrets.TEST_ENV }}
          TEST_FIREBASE: ${{ secrets.TEST_FIREBASE }}
        run: |
          printf "%s" "${TEST_ENV}" > ./server/api/config/.env.test
          printf "%s" "${TEST_FIREBASE}" > ./server/api/config/firebaseKey.json
          sudo chown -R 1000:1000 $(pwd)

      - name: start database
        shell: bash
        run: ./server.sh db start

      - name: test api
        shell: bash
        run: ./server.sh api test --coverage
